<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Foundations - 5&nbsp; Model Selection</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-diagnostics.html" rel="next">
<link href="./03-complex_ANOVA_Regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Selection</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Foundations</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-introduction_ANOVA_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to ANOVA and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-complex_ANOVA_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Complex ANOVA and Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-model_selection.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Selection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Diagnostics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-model_building_scoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Building &amp; Scoring for Prediction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-categorical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#selection-criteria" id="toc-selection-criteria" class="nav-link active" data-scroll-target="#selection-criteria"><span class="toc-section-number">5.1</span>  Selection Criteria</a></li>
  <li><a href="#stepwise-selection" id="toc-stepwise-selection" class="nav-link" data-scroll-target="#stepwise-selection"><span class="toc-section-number">5.2</span>  Stepwise Selection</a>
  <ul class="collapse">
  <li><a href="#forward" id="toc-forward" class="nav-link" data-scroll-target="#forward">Forward</a></li>
  <li><a href="#backward" id="toc-backward" class="nav-link" data-scroll-target="#backward">Backward</a></li>
  <li><a href="#stepwise" id="toc-stepwise" class="nav-link" data-scroll-target="#stepwise">Stepwise</a></li>
  </ul></li>
  <li><a href="#significance-levels" id="toc-significance-levels" class="nav-link" data-scroll-target="#significance-levels"><span class="toc-section-number">5.3</span>  Significance Levels</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-sel" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Selection</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This section will dive into some basic foundations in model selection, or finding the best model for a data set. In most data sets, there will most likely be variables that are informative and ones that are uninformative in predicting the response. With many explanatory variables, it could be extremely time consuming to try all potential models by hand, and the use of automatic procedures can greatly assist in obtaining subsets of variables in which to focus your attention.<br>
</p>
<ul>
This Chapter aims to answer the following questions:
</ul>
<li>
<p>What are the different selection criteria that can be used in model selection?</p>

</li><li>
<p>How to perform a stepwise search algorithm.</p>
<ul>
<li>
<p>Forward Selection</p>
</li><li>
<p>Backward Elimination</p>
</li><li>
<p>Stepwise Selection</p>
</li></ul>
</li><li>
<p>Considerations when looking at p-values.</p>
<ul>
<p>CAUTION: you should NEVER just use the final model created from an automatic procedure! <em>Always</em> explore your data (both automatically selected <em>and</em> excluded variables), and use domain knowledge, diagnostics, and critical thought to decide on your final model.</p>
<p>We will focus on two techniques for automatic variable selection: stepwise procedures and LASSO. Within the stepwise procedures, we will discuss forward, backward and stepwise searches using several different selection criteria. We will end this section discussing important considerations in use of p-values when dealing with large data sets.</p>
<section id="selection-criteria" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="selection-criteria"><span class="header-section-number">5.1</span> Selection Criteria</h2>
<p>When trying to find the best model, there are many selection criteria at our disposal. For example, you have already been introduced to <span class="math inline">\(R^{2}\)</span> (the larger the value of <span class="math inline">\(R^{2}\)</span>, the better the model). However, when comparing multivariate models, the adjusted <span class="math inline">\(R^{2}\)</span> is better due to the fact that <span class="math inline">\(R^{2}\)</span> can potentially increase even when adding noise. The adjusted <span class="math inline">\(R^{2}\)</span> can be thought of as <span class="math inline">\(R^{2}\)</span> with penalty (for every additional variable added to the model, we add a penalty). This allows us to weigh the contribution of adding new variables against the added complexity of more variables in the model. There are other selection criteria that are also used in selecting the “best model” (or variable selection). As you will notice, these selection criteria also have a penalty to take into account the addition of variables. We will use two of the most common ones: AIC and BIC (can also be referred to as SBC).</p>
<p>The AIC, or <strong>Akaike Information Criterion</strong>, was developed by statistician Hirotugu Akaike in the 1970’s and is defined by <span class="math display">\[ AIC = -2log(Likelihood) + 2p.  \]</span> In this case, “Likelihood” is the likelihood of the data and <span class="math inline">\(2p\)</span> is the “penalty”, where <span class="math inline">\(p\)</span> is the number of parameters in the model. A smaller AIC indicates a better model.</p>
<p>BIC, also known as the <strong>Bayesian Information Criterion</strong> (also called SBC or <strong>Schwarz Bayesian Information</strong>) was first developed by Gideon E. Schwarz, also back in the 1970’s and is defined by <span class="math display">\[BIC = -2log(Likelihood) + plog(n). \]</span> In this case, “Likelihood” is the likelihood of the data and <span class="math inline">\(plog(n)\)</span> is the “penalty”, where <span class="math inline">\(p\)</span> is the number of parameters in the model and <span class="math inline">\(n\)</span> is the sample size. A smaller BIC indicates a better model. Notice that both penalties have a common term of <span class="math inline">\(p\)</span> in them (this will be important to remember when we start discussing the R code).</p>
</section>
<section id="stepwise-selection" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="stepwise-selection"><span class="header-section-number">5.2</span> Stepwise Selection</h2>
<p>The three different algorithms in the stepwise selection search are forward, backward and stepwise. Each of these algorithms either add or take away one variable at a time based on a given criterion until this criterion can no longer be met. At which point the algorithm stops.</p>
<div class="cell">

</div>
<section id="forward" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="forward">Forward</h3>
<p>For forward selection, we start with a null model (only the intercept) and add one variable at a time until no other variables can be added based on a given criterion. The algorithm is as follows:</p>
<ol start="0" type="1">
<li>Start with a null model, this is the base model (just the intercept)<br>

<ol type="1">
<li>For each variable not in model, create a linear regression model with the base model plus this one variable<br>
</li>
<li>See which linear regression is best (based on criterion)<br>
</li>
<li>Is this regression better than the base model?<br>

<ol type="a">
<li>Yes, then continue on to step 4<br>
</li>
<li>No, exit the algorithm with the base model as the chosen model<br>
</li>
</ol></li>
<li>The base model is now the previous base model plus the variable selected in step 3. Using this as your new base model, go back to step 1 and continue.<br>
</li>
</ol></li>
</ol>
<p>To do forward selection in R, you will use the step function. The “empty model” should be used as your initial model (which is just the intercept). For the scope of the model, you need to put the “smallest model” (just the intercept) to the “largest model” (full model). The direction is forward. The penalty can be controlled by defining “<span class="math inline">\(k\)</span>”. Using a value of 2 for “<span class="math inline">\(k\)</span>” will use the AIC criterion (remember AIC penalty was <span class="math inline">\(2p\)</span>) and using <span class="math inline">\(log(n)\)</span> for “<span class="math inline">\(k\)</span>” will use the BIC criterion (remember BIC penalty was <span class="math inline">\(plog(n)\)</span>). If you do not specify anything for “<span class="math inline">\(k\)</span>”, the default is AIC. You can also define “<span class="math inline">\(k\)</span>” as the upper <span class="math inline">\(\alpha\)</span>-quantile of a <span class="math inline">\(\chi^{2}\)</span> distribution with one degree of freedom, which will use p-value for its selection of variables. In this case, the best “model” is the one with the lowest p-value for the new variable. In order to enter the model, the p-value of this variable will need to be lower than the “cut-off” for the p-values (<span class="math inline">\(\alpha\)</span>), which means that the criterion to enter the model would be that the variable has a p-value smaller than <span class="math inline">\(\alpha\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create full model and empty model</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> . , <span class="at">data =</span> train_sel)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_sel)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># k = 2 for AIC selection</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>for.model <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> full.model),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">k =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Below is edited output with comments to lead you through the forward selection. Notice that the above code has <span class="math inline">\(k\)</span>=2, which means we are using AIC as our selection criterion. The first information R provides is for the initial model, which is <span class="math display">\[Y_{i}=\beta_{0} + \varepsilon_{i}.\]</span> The “empty model” has an AIC of 46,323.64 (in order for ANY variable to be added, that model must be better, or in other words have a smaller AIC than this initial model).</p>
<pre><code>Start:  AIC=46323.64
Sale_Price ~ 1</code></pre>
<p>R then displays all simple linear regressions with their corresponding AIC values. Notice that R puts the information in ascending AIC values (so, the best simple linear regression is 43,817 which is indeed smaller than 46,323.64). You will also see a line with a blank for the “variable”, this is the current “base model”. In this first step, it is just the intercept. Therefore, we will add the variable Overall_Qual.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">9.3437e+12</td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43817</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.4389e+12</td>
<td style="text-align: center;">6.7578e+12</td>
<td style="text-align: right;">44953</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">5.3561e+12</td>
<td style="text-align: center;">7.8407e+12</td>
<td style="text-align: right;">45258</td>
</tr>
<tr class="even">
<td style="text-align: left;">+First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.8867e+12</td>
<td style="text-align: center;">8.3100e+12</td>
<td style="text-align: right;">45377</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.7827e+12</td>
<td style="text-align: center;">9.4141e+12</td>
<td style="text-align: right;">45633</td>
</tr>
<tr class="even">
<td style="text-align: left;">+TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.2304e+12</td>
<td style="text-align: center;">9.9663e+12</td>
<td style="text-align: right;">45750</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.9715e+12</td>
<td style="text-align: center;">1.0225e+13</td>
<td style="text-align: right;">45802</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.1209e+12</td>
<td style="text-align: center;">1.2076e+13</td>
<td style="text-align: right;">46144</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">1.0724e+12</td>
<td style="text-align: center;">1.2124e+13</td>
<td style="text-align: right;">46160</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.6147e+11</td>
<td style="text-align: center;">1.2235e+13</td>
<td style="text-align: right;">46170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">1.0245e+12</td>
<td style="text-align: center;">1.2172e+13</td>
<td style="text-align: right;">46172</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.4611e+11</td>
<td style="text-align: center;">1.2251e+13</td>
<td style="text-align: right;">46173</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.0332e+11</td>
<td style="text-align: center;">1.2293e+13</td>
<td style="text-align: right;">46180</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">4.6434e+11</td>
<td style="text-align: center;">1.2732e+13</td>
<td style="text-align: right;">46258</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.1752e+10</td>
<td style="text-align: center;">1.3165e+13</td>
<td style="text-align: right;">46321</td>
</tr>
<tr class="even">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;">1.3197e+13</td>
<td style="text-align: center;">46324</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>Now, R shows you the new “base model”, which includes Overall_Qual (and of course the intercept is still included) and the new AIC value to beat which is 43816.66.</p>
<pre><code>Step:  AIC=43816.66
Sale_Price ~ Overall_Qual</code></pre>
<p>Using this as our base model, we now try adding each of the remaining variables in separate regression models, output is shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.8905e+11</td>
<td style="text-align: center;">2.8640e+12</td>
<td style="text-align: right;">43210</td>
</tr>
<tr class="even">
<td style="text-align: left;">+First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">5.2665e+11</td>
<td style="text-align: center;">3.3264e+12</td>
<td style="text-align: right;">43517</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.6644e+11</td>
<td style="text-align: center;">3.3866e+12</td>
<td style="text-align: right;">43554</td>
</tr>
<tr class="even">
<td style="text-align: left;">+TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.6123e+11</td>
<td style="text-align: center;">3.3918e+12</td>
<td style="text-align: right;">43557</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.1206e+11</td>
<td style="text-align: center;">3.4410e+12</td>
<td style="text-align: right;">43587</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.0551e+11</td>
<td style="text-align: center;">3.4476e+12</td>
<td style="text-align: right;">43591</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.8148e+11</td>
<td style="text-align: center;">3.4716e+12</td>
<td style="text-align: right;">43605</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">2.3715e+11</td>
<td style="text-align: center;">3.6159e+12</td>
<td style="text-align: right;">43694</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.7555e+11</td>
<td style="text-align: center;">3.6775e+12</td>
<td style="text-align: right;">43723</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.3948e+11</td>
<td style="text-align: center;">3.7136e+12</td>
<td style="text-align: right;">43743</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.1322e+10</td>
<td style="text-align: center;">3.7617e+12</td>
<td style="text-align: right;">43769</td>
</tr>
<tr class="even">
<td style="text-align: left;">+House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">6.1815e+10</td>
<td style="text-align: center;">3.7912e+12</td>
<td style="text-align: right;">43797</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">5.1448e+10</td>
<td style="text-align: center;">3.8016e+12</td>
<td style="text-align: right;">43799</td>
</tr>
<tr class="even">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.9573e+06</td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43819</td>
</tr>
</tbody>
</table>
<p>Best model includes Gr_Liv_Area (in addition to the intercept and Overall_Qual). The AIC is 43210, which beats the previous one of 43817. So, we will add Gr_Liv_Area to the model. Our new base model includes the intercept, Overall_Qual and Gr_Liv_Area with an AIC of 43210.</p>
<pre><code>Step:  AIC=43210.24
Sale_Price ~ Overall_Qual + Gr_Liv_Area</code></pre>
<p>We continue in this fashion until adding a new variable does NOT decrease the AIC. The last step is shown below:</p>
<pre><code>Step:  AIC=42676.1
Sale_Price ~ Overall_Qual + Gr_Liv_Area + House_Style + Garage_Area + Bldg_Type + Fireplaces 
        + Full_Bath + Half_Bath + Lot_Area + Roof_Style + Central_Air + Second_Flr_SF 
        + TotRms_AbvGrd + First_Flr_SF</code></pre>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">2.1542e+12</td>
<td style="text-align: right;">42676</td>
</tr>
<tr class="even">
<td style="text-align: left;">+Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.028e+09</td>
<td style="text-align: center;">2.1532e+12</td>
<td style="text-align: right;">42677</td>
</tr>
</tbody>
</table>
<p>Notice that the previous step had a model with the intercept, Overall_Qual, Gr_Liv_Area, House_Style, Garage_Area, Bldg_Type, Fireplaces, Full_Bath, Half_Bath, Lot_Area, Roof_Style, Central_Air, Second_Flr_SF, TotRms_AbvGrd, and First_Flr_SF (as illustrated by the above formula). The AIC for this model is 42676.1. There is only one variable left that could be added (Street). However, when we add street to the model, the AIC now becomes 42677 (in other words AIC increases, which is a worse model). The algorithm stops here.</p>
<p>The code below illustrates how to do forward selection with BIC and p-values. In the output from R, it still says “AIC”, but now these values are calculated by using the BIC formula or the corresponding “<span class="math inline">\(k\)</span>” values for p-values (take a look at the values R has for the “AIC” column and you will see that it has changed!).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># k = log(n) for BIC selection</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>for.model2 <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> full.model),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(train_sel))) <span class="co"># k = qchisq(alpha, 1, lower.tail = FALSE) for p-value with alpha selection</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>alpha.f<span class="ot">=</span><span class="fl">0.05</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>for.model3 <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">upper =</span> full.model),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">k =</span> <span class="fu">qchisq</span>(alpha.f, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="backward" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="backward">Backward</h3>
<p>Backward elimination starts with the “base” model as the full model (i.e.&nbsp;all variables are contained within the model). We remove only one variable and we do this for each variable in the model. We want to see if the any of the models improve over the “base model” (in other words, is the model better with that one variable removed based on a given criterion?). If this new model (with that one variable removed) is better than the previous model, then we remove that variable and this new model now becomes the base model. We are looking for the best improvement, therefore we look at the model that would be the best over the base model. The algorithm continues in this fashion until no other variables can be removed, based on the chosen criterion.</p>
<ol start="0" type="1">
<li>Start with full model with all predictor variables in it, this is the base model and calculate the criterion on this model<br>

<ol type="1">
<li>Create models such that each model has exactly one predictor variable removed from it and calculate the criterion for each model<br>
</li>
<li>In step 1, find the best model based on the criterion<br>
</li>
<li>Is this regression model better than the base model?<br>

<ol type="a">
<li>Yes, then continue on to step 4<br>
</li>
<li>No, exit the algorithm with the base model as the chosen model<br>
</li>
</ol></li>
<li>The base model is now the model with the variable removed. Using this as your new base model, go back to step 1 and continue.<br>
</li>
</ol></li>
</ol>
<p>To do backward elimination in R, you will use the step function. The “full model” should be used as your initial model (which is the model with all the predictor variables in it). For the scope of the model, you need to put the “smallest model” (just the intercept) to the “largest model” (full model). The direction is backward. The penalty (which indicates the criteria) can be controlled by defining “<span class="math inline">\(k\)</span>”. As discussed before, a value of 2 will use the AIC criterion, a value of <span class="math inline">\(log(n)\)</span> will produce the BIC penalty, and finally the upper <span class="math inline">\(\alpha\)</span>-quantile of a <span class="math inline">\(\chi^{2}\)</span> distribution with one degree of freedom will use p-value for its removal of variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create full model and empty model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> . , <span class="at">data =</span> train_sel)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_sel)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># k = 2 for AIC selection</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>back.model <span class="ot">&lt;-</span> <span class="fu">step</span>(full.model,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> full.model),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Below is edited output with comments to lead you through the backward elimination. Notice that the above code has <span class="math inline">\(k\)</span>=2, which means we are using AIC as our selection criterion. The first information R provides is for the initial model, which is <span class="math display">\[Y_{i}=\beta_{0} + \beta_{1}x_{i,1}+\beta_{2}x_{i,2}+\beta_{3}x_{i,3}+\beta_{4}x_{i,4}+\beta_{5}x_{i,5}+\beta_{6}x_{i,6}+\beta_{i,7}x_{7}+\beta_{8}x_{i,8}+\beta_{9}x_{i,9}+\beta_{10}x_{i,10}+\beta_{11}x_{i,11}+\beta_{12}x_{i,12}+\beta_{13}x_{i,13}+\beta_{14}x_{i,14}+\beta_{15}x_{i,15}+\varepsilon_{i}.\]</span> The “full model” has an AIC of 42,677.12 (in order for ANY variable to be removed, that model must be better, or in other words have a smaller AIC than this initial model).</p>
<p>R then displays linear regression models with one variable removed and their corresponding AIC values. For example, if we remove Street (just that one variable), the AIC of that model will be 42675. Notice that R put the information in ascending AIC values (so, best linear regression is at the top with an AIC value of 42,675 which is indeed smaller than 42,677.12, so Street will be removed). You will also see a line with <none>. This is the “base model”, or in this case the full model.</none></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">- Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.9138e+08</td>
<td style="text-align: center;">2.1537e+12</td>
<td style="text-align: right;">42676</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.0280e+09</td>
<td style="text-align: center;">2.1542e+12</td>
<td style="text-align: right;">42676</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">2.1532e+12</td>
<td style="text-align: right;">42677</td>
</tr>
<tr class="even">
<td style="text-align: left;">- First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.1548e+09</td>
<td style="text-align: center;">2.1563e+12</td>
<td style="text-align: right;">42678</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.4112e+09</td>
<td style="text-align: center;">2.1566e+12</td>
<td style="text-align: right;">42678</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.4939e+09</td>
<td style="text-align: center;">2.1597e+12</td>
<td style="text-align: right;">42681</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.6533e+10</td>
<td style="text-align: center;">2.1697e+12</td>
<td style="text-align: right;">42691</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">2.8786e+10</td>
<td style="text-align: center;">2.1820e+12</td>
<td style="text-align: right;">42694</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.5009e+10</td>
<td style="text-align: center;">2.1882e+12</td>
<td style="text-align: right;">42708</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.5997e+10</td>
<td style="text-align: center;">2.1892e+12</td>
<td style="text-align: right;">42709</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.6853e+10</td>
<td style="text-align: center;">2.1900e+12</td>
<td style="text-align: right;">42710</td>
</tr>
<tr class="even">
<td style="text-align: left;">- House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">7.0980e+10</td>
<td style="text-align: center;">2.2241e+12</td>
<td style="text-align: right;">42730</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.4143e+10</td>
<td style="text-align: center;">2.2173e+12</td>
<td style="text-align: right;">42735</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">7.1274e+10</td>
<td style="text-align: center;">2.2244e+12</td>
<td style="text-align: right;">42736</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.8198e+10</td>
<td style="text-align: center;">2.2214e+12</td>
<td style="text-align: right;">42739</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">1.7183e+12</td>
<td style="text-align: center;">3.8715e+12</td>
<td style="text-align: right;">43862</td>
</tr>
</tbody>
</table>
<p>Once Street is removed, the new “base model” (without this variable) has an AIC value of 42,674.6. This is now the new value to beat. Repeating this process with removing the other variables one at a time, we see the output:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">2.1547e+12</td>
<td style="text-align: right;">42675</td>
</tr>
<tr class="even">
<td style="text-align: left;">- TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.9784e+09</td>
<td style="text-align: center;">2.1577e+12</td>
<td style="text-align: right;">42675</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.7247e+10</td>
<td style="text-align: center;">2.1720e+12</td>
<td style="text-align: right;">42689</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">2.8560e+10</td>
<td style="text-align: center;">2.1833e+12</td>
<td style="text-align: right;">42692</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.4751e+10</td>
<td style="text-align: center;">2.1895e+12</td>
<td style="text-align: right;">42705</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.5041e+10</td>
<td style="text-align: center;">2.1898e+12</td>
<td style="text-align: right;">42706</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.6680e+10</td>
<td style="text-align: center;">2.1914e+12</td>
<td style="text-align: right;">42707</td>
</tr>
<tr class="even">
<td style="text-align: left;">- House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">7.3149e+10</td>
<td style="text-align: center;">2.2279e+12</td>
<td style="text-align: right;">42729</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.3520e+10</td>
<td style="text-align: center;">2.2182e+12</td>
<td style="text-align: right;">42732</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">7.3044e+10</td>
<td style="text-align: center;">2.2278e+12</td>
<td style="text-align: right;">42735</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.8973e+10</td>
<td style="text-align: center;">2.2237e+12</td>
<td style="text-align: right;">42737</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.2513e+11</td>
<td style="text-align: center;">2.2798e+12</td>
<td style="text-align: right;">42788</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.4221e+11</td>
<td style="text-align: center;">2.2969e+12</td>
<td style="text-align: right;">42804</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">1.7202e+12</td>
<td style="text-align: center;">3.8749e+12</td>
<td style="text-align: right;">43860</td>
</tr>
</tbody>
</table>
<p>Notice that none of the removal of variables is better than the “base model” based on the AIC (best one is TotRms_AbvGrd and that has an AIC of 42675, which is not better than the base model). Since none of the removals improve the model, the algorithm stops here with all variables in the model except Street. A quick note here: notice that backward elimination selected the same model as forward selection. This will not always be the case! Therefore, the final model is:</p>
<pre><code>Step:  AIC=42674.6
Sale_Price ~ Lot_Area + Bldg_Type + House_Style + Overall_Qual + 
    Roof_Style + Central_Air + First_Flr_SF + Second_Flr_SF + 
    Full_Bath + Half_Bath + Fireplaces + Garage_Area + TotRms_AbvGrd</code></pre>
<p>The code below illustrates how to do backward elimination with BIC and p-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># k = log(n) for BIC selection</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>back.model2 <span class="ot">&lt;-</span> <span class="fu">step</span>(full.model,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> full.model),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(train_sel))) <span class="co"># k = qchisq(alpha, 1, lower.tail = FALSE) for p-value with alpha selection</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>alpha.f<span class="ot">=</span><span class="fl">0.05</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>back.model3 <span class="ot">&lt;-</span> <span class="fu">step</span>(full.model,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">upper =</span> full.model),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="fu">qchisq</span>(alpha.f, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="stepwise" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="stepwise">Stepwise</h3>
<p>Stepwise selection is a combination of both of these methods. In this algorithm, we start with the “base model” as the empty model (i.e.&nbsp;just the intercept) and will add variables (as in forward selection). However, as we add new variables, we will also check that the variables in the model are still contributing (in other words, after a new variable is added, we check to see if the model would be better if we drop one of the other variables in the model). Keep in mind that this algorithm is similar to forward selection and backward elimination in that only one variable may either enter or be removed at each step. The algorithm stops when no more variables can be added to nor taken away from the model (in other words, the current “base model” is better than adding any single addition of one variable or any single extraction of one variable). The addition and removal of variables is again based upon the criteria specified. See the algorithm below:</p>
<ol start="0" type="1">
<li>Start with empty model with only the intercept in it, this is the base model and calculate the criterion on this model<br>

<ol type="1">
<li>For each variable not in model, create a linear regression model with the base model plus this variable; create additional models with the base model taking away one variable at a time<br>
</li>
<li>See which linear regression is best (based on criterion)<br>
</li>
<li>Is this regression better than the base model?<br>

<ol type="a">
<li>Yes, then continue on to step 4<br>
</li>
<li>No, exit the algorithm with the base model as the chosen model<br>
</li>
</ol></li>
<li>The base model is now the best model selected in step 3. Using this as your new base model, go back to step 1 and continue.<br>
</li>
</ol></li>
</ol>
<p>To do stepwise selection in R, you will use the step function. The “empty model” should be used as your initial model. For the scope of the model, you need to put the “smallest model” (just the intercept) to the “largest model” (full model). The direction is both. The penalty (which indicates the criteria) can be controlled by defining “<span class="math inline">\(k\)</span>”. As discussed before, a value of 2 will use the AIC criterion, a value of <span class="math inline">\(log(n)\)</span> will produce the BIC penalty, and finally the upper <span class="math inline">\(\alpha\)</span>-quantile of a <span class="math inline">\(\chi^{2}\)</span> distribution with one degree of freedom will use p-value for its removal of variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create full model and empty model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> . , <span class="at">data =</span> train_sel)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sale_Price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_sel)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># k = 2 for AIC selection</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>step.model <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty.model,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> full.model),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">k =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, the initial base model is just the intercept (AIC=46,323.64). From this initial model, all simple linear regressions are created and the AIC is observed.</p>
<pre><code>Start:  AIC=46323.64
Sale_Price ~ 1</code></pre>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+ Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">9.3437e+12</td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43817</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.4389e+12</td>
<td style="text-align: center;">6.7578e+12</td>
<td style="text-align: right;">44953</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">5.3561e+12</td>
<td style="text-align: center;">7.8407e+12</td>
<td style="text-align: right;">45258</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.8867e+12</td>
<td style="text-align: center;">8.3100e+12</td>
<td style="text-align: right;">45377</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.7827e+12</td>
<td style="text-align: center;">9.4141e+12</td>
<td style="text-align: right;">45633</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.2304e+12</td>
<td style="text-align: center;">9.9663e+12</td>
<td style="text-align: right;">45750</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.9715e+12</td>
<td style="text-align: center;">1.0225e+13</td>
<td style="text-align: right;">45802</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.1209e+12</td>
<td style="text-align: center;">1.2076e+13</td>
<td style="text-align: right;">46144</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">1.0724e+12</td>
<td style="text-align: center;">1.2124e+13</td>
<td style="text-align: right;">46160</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.6147e+11</td>
<td style="text-align: center;">1.2235e+13</td>
<td style="text-align: right;">46170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">1.0245e+12</td>
<td style="text-align: center;">1.2172e+13</td>
<td style="text-align: right;">46172</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.4611e+11</td>
<td style="text-align: center;">1.2251e+13</td>
<td style="text-align: right;">46173</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.0332e+11</td>
<td style="text-align: center;">1.2293e+13</td>
<td style="text-align: right;">46180</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">4.6434e+11</td>
<td style="text-align: center;">1.2732e+13</td>
<td style="text-align: right;">46258</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.1752e+10</td>
<td style="text-align: center;">1.3165e+13</td>
<td style="text-align: right;">46321</td>
</tr>
<tr class="even">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">1.3197e+13</td>
<td style="text-align: right;">46324</td>
</tr>
</tbody>
</table>
<p>As you can see from the above output, the “best” model is the one containing Overall_Qual. Therefore, the new base model is the one containing just this variable. &nbsp;</p>
<p>Using this as the new base model, we look at adding each of the individual variables to this model (see output below), as well as taking away the variables in the model (in this case, just Overall_Qual). From the output, you can see a “+” for when a variable is being added and a “-” for when a variable is being taken away.</p>
<pre><code>Step:  AIC=43816.66
Sale_Price ~ Overall_Qual</code></pre>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+ Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.8905e+11</td>
<td style="text-align: center;">2.8640e+12</td>
<td style="text-align: right;">43210</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">5.2665e+11</td>
<td style="text-align: center;">3.3264e+12</td>
<td style="text-align: right;">43517</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.6644e+11</td>
<td style="text-align: center;">3.3866e+12</td>
<td style="text-align: right;">43554</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.6123e+11</td>
<td style="text-align: center;">3.3918e+12</td>
<td style="text-align: right;">43557</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.1206e+11</td>
<td style="text-align: center;">3.4410e+12</td>
<td style="text-align: right;">43587</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.0551e+11</td>
<td style="text-align: center;">3.4476e+12</td>
<td style="text-align: right;">43591</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.8148e+11</td>
<td style="text-align: center;">3.4716e+12</td>
<td style="text-align: right;">43605</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">2.3715e+11</td>
<td style="text-align: center;">3.6159e+12</td>
<td style="text-align: right;">43694</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.7555e+11</td>
<td style="text-align: center;">3.6775e+12</td>
<td style="text-align: right;">43723</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.3948e+11</td>
<td style="text-align: center;">3.7136e+12</td>
<td style="text-align: right;">43743</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.1322e+10</td>
<td style="text-align: center;">3.7617e+12</td>
<td style="text-align: right;">43769</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">6.1815e+10</td>
<td style="text-align: center;">3.7912e+12</td>
<td style="text-align: right;">43797</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">5.1448e+10</td>
<td style="text-align: center;">3.8016e+12</td>
<td style="text-align: right;">43799</td>
</tr>
<tr class="even">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.9573e+06</td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43819</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">9.3437e+12</td>
<td style="text-align: center;">1.3197e+13</td>
<td style="text-align: right;">46324</td>
</tr>
</tbody>
</table>
<p>The best model is now the one adding <code>Gr_Liv_Area</code> to the old base model that just included <code>Overall_Qual</code>. This becomes the new base model and the algorithm continues below..</p>
<pre><code>Step:  AIC=43210.24
Sale_Price ~ Overall_Qual + Gr_Liv_Area</code></pre>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+ House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">2.5351e+11</td>
<td style="text-align: center;">2.6105e+12</td>
<td style="text-align: right;">43034</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.1638e+11</td>
<td style="text-align: center;">2.6476e+12</td>
<td style="text-align: right;">43051</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.3097e+11</td>
<td style="text-align: center;">2.7330e+12</td>
<td style="text-align: right;">43116</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.2210e+11</td>
<td style="text-align: center;">2.7419e+12</td>
<td style="text-align: right;">43123</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.1069e+11</td>
<td style="text-align: center;">2.7533e+12</td>
<td style="text-align: right;">43131</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.1050e+11</td>
<td style="text-align: center;">2.7535e+12</td>
<td style="text-align: right;">43132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.0207e+11</td>
<td style="text-align: center;">2.7619e+12</td>
<td style="text-align: right;">43138</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">1.0299e+11</td>
<td style="text-align: center;">2.7610e+12</td>
<td style="text-align: right;">43143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">6.0726e+10</td>
<td style="text-align: center;">2.8033e+12</td>
<td style="text-align: right;">43176</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.2970e+10</td>
<td style="text-align: center;">2.8310e+12</td>
<td style="text-align: right;">43188</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.4688e+10</td>
<td style="text-align: center;">2.8393e+12</td>
<td style="text-align: right;">43194</td>
</tr>
<tr class="even">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">2.8640e+12</td>
<td style="text-align: right;">43210</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">4.0261e+07</td>
<td style="text-align: center;">2.8640e+12</td>
<td style="text-align: right;">43212</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.2632e+07</td>
<td style="text-align: center;">2.8640e+12</td>
<td style="text-align: right;">43212</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">9.8905e+11</td>
<td style="text-align: center;">3.8531e+12</td>
<td style="text-align: right;">43817</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">3.8938e+12</td>
<td style="text-align: center;">6.7578e+12</td>
<td style="text-align: right;">44953</td>
</tr>
</tbody>
</table>
<p>Skipping ahead to the final step, we see that the base model includes the variables Overall_Qual, House_Style, Garage_Area, Bldg_Type, Fireplaces, Full_Bath, Half_Bath, Lot_Area, Roof_Style, Central_Air, Second_Flr_SF, TotRms_AbvGrd and First_Flr_SF. Looking at the output below, this is the “best model” (no other model, either inputting one more variable nor removing one variable can beat it based on this criteria).</p>
<pre><code>Step:  AIC=42674.6
Sale_Price ~ Overall_Qual + House_Style + Garage_Area + Bldg_Type + 
    Fireplaces + Full_Bath + Half_Bath + Lot_Area + Roof_Style + 
    Central_Air + Second_Flr_SF + TotRms_AbvGrd + First_Flr_SF</code></pre>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: center;">RSS</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><none></none></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;">2.1547e+12</td>
<td style="text-align: right;">42675</td>
</tr>
<tr class="even">
<td style="text-align: left;">- TotRms_AbvGrd</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">2.9784e+09</td>
<td style="text-align: center;">2.1577e+12</td>
<td style="text-align: right;">42675</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ Street</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.0581e+09</td>
<td style="text-align: center;">2.1537e+12</td>
<td style="text-align: right;">42676</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ Gr_Liv_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">5.2156e+08</td>
<td style="text-align: center;">2.1542e+12</td>
<td style="text-align: right;">42676</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Central_Air</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.7247e+10</td>
<td style="text-align: center;">2.1720e+12</td>
<td style="text-align: right;">42689</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Roof_Style</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">2.8560e+10</td>
<td style="text-align: center;">2.1833e+12</td>
<td style="text-align: right;">42692</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Half_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.4751e+10</td>
<td style="text-align: center;">2.1895e+12</td>
<td style="text-align: right;">42705</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Lot_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.5041e+10</td>
<td style="text-align: center;">2.1898e+12</td>
<td style="text-align: right;">42706</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Fireplaces</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">3.6680e+10</td>
<td style="text-align: center;">2.1914e+12</td>
<td style="text-align: right;">42707</td>
</tr>
<tr class="even">
<td style="text-align: left;">- House_Style</td>
<td style="text-align: center;">7</td>
<td style="text-align: right;">7.3149e+10</td>
<td style="text-align: center;">2.2279e+12</td>
<td style="text-align: right;">42729</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Garage_Area</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.3520e+10</td>
<td style="text-align: center;">2.2182e+12</td>
<td style="text-align: right;">42732</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Bldg_Type</td>
<td style="text-align: center;">4</td>
<td style="text-align: right;">7.3044e+10</td>
<td style="text-align: center;">2.2278e+12</td>
<td style="text-align: right;">42735</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- Full_Bath</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">6.8973e+10</td>
<td style="text-align: center;">2.2237e+12</td>
<td style="text-align: right;">42737</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Second_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.2513e+11</td>
<td style="text-align: center;">2.2798e+12</td>
<td style="text-align: right;">42788</td>
</tr>
<tr class="odd">
<td style="text-align: left;">- First_Flr_SF</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1.4221e+11</td>
<td style="text-align: center;">2.2969e+12</td>
<td style="text-align: right;">42804</td>
</tr>
<tr class="even">
<td style="text-align: left;">- Overall_Qual</td>
<td style="text-align: center;">9</td>
<td style="text-align: right;">1.7202e+12</td>
<td style="text-align: center;">3.8749e+12</td>
<td style="text-align: right;">43860</td>
</tr>
</tbody>
</table>
<p>As you can see from the above stepwise procedures of forward, backward and stepwise, the algorithms attempt to find the “best model” by either adding one variable or taking away one variable at at a time. There is no guarantee that these algorithms will find the best model, but they do provide some guidance in terms of potential significance variables and can provide assistance when the number of variables under consideration is very large. As a caution though, you should always do further investigation once you have found models through these algorithms. These algorithms can give the same models or different models as their final selection based on the algorithm selected and the criteria used.</p>
</section>
</section>
<section id="significance-levels" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="significance-levels"><span class="header-section-number">5.3</span> Significance Levels</h2>
<p>If you are going to use the “p-value” method, you need to be aware of some considerations due to sample size. The larger the sample size, the smaller the p-values will be and the more likely it is that you will end up seeing many “significant” p-values due to the relationship between p-values and sample size (not necessarily because that variable was informative). The paper by Raftery on the Moodle page sums up the problem nicely and provides at least some guidance in terms of potential alpha-levels to use for different sample sizes. A summary of the table is provided below.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Evidence</th>
<th style="text-align: right;">30</th>
<th style="text-align: right;">50</th>
<th style="text-align: right;">100</th>
<th style="text-align: right;">1000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Weak</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fair</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Strong</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.0003</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very Strong</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.0005</td>
<td style="text-align: right;">0.0001</td>
<td style="text-align: right;">0.00004</td>
</tr>
</tbody>
</table>
<p>You can quickly see that for even sample sizes of 1000, one should consider the value of alpha that is used to determine significance. One thing that most researchers agree on is that considerations need to be taken for larger sample size. However, what those considerations should be and exactly how to do that is not agreed upon. You should consider your sample size when you are determining what level of significance you want to choose for your analysis (also take into account which is worse….a type I error or a type II error). There is no quick answer to this question and each decision will depend on the analysis being conducted.</p>


</section>

</ul></li></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-complex_ANOVA_Regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Complex ANOVA and Multiple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-diagnostics.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Diagnostics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>