<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Foundations - 8&nbsp; Categorical Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-model_building_scoring.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Foundations</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-introduction_ANOVA_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to ANOVA and Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-complex_ANOVA_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Complex ANOVA and Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-model_selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Selection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Diagnostics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-model_building_scoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Building &amp; Scoring for Prediction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-categorical.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#describing-categorical-data" id="toc-describing-categorical-data" class="nav-link active" data-scroll-target="#describing-categorical-data"><span class="toc-section-number">8.1</span>  Describing Categorical Data</a></li>
  <li><a href="#tests-of-association" id="toc-tests-of-association" class="nav-link" data-scroll-target="#tests-of-association"><span class="toc-section-number">8.2</span>  Tests of Association</a></li>
  <li><a href="#measures-of-association" id="toc-measures-of-association" class="nav-link" data-scroll-target="#measures-of-association"><span class="toc-section-number">8.3</span>  Measures of Association</a></li>
  <li><a href="#introduction-to-logistic-regression" id="toc-introduction-to-logistic-regression" class="nav-link" data-scroll-target="#introduction-to-logistic-regression"><span class="toc-section-number">8.4</span>  Introduction to Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#linear-probability-model" id="toc-linear-probability-model" class="nav-link" data-scroll-target="#linear-probability-model"><span class="toc-section-number">8.4.1</span>  Linear Probability Model</a></li>
  <li><a href="#binary-logistic-regression" id="toc-binary-logistic-regression" class="nav-link" data-scroll-target="#binary-logistic-regression"><span class="toc-section-number">8.4.2</span>  Binary Logistic Regression</a></li>
  <li><a href="#adding-categorical-variables" id="toc-adding-categorical-variables" class="nav-link" data-scroll-target="#adding-categorical-variables"><span class="toc-section-number">8.4.3</span>  Adding Categorical Variables</a></li>
  <li><a href="#model-assessment" id="toc-model-assessment" class="nav-link" data-scroll-target="#model-assessment"><span class="toc-section-number">8.4.4</span>  Model Assessment</a></li>
  <li><a href="#variable-selection-and-regularized-regression" id="toc-variable-selection-and-regularized-regression" class="nav-link" data-scroll-target="#variable-selection-and-regularized-regression"><span class="toc-section-number">8.4.5</span>  Variable Selection and Regularized Regression</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-cat" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Everything analysis covered so far has used a continuous variable as a target variable of interest. What if our target variable was categorical instead of continuous? Our analysis must change to adjust.</p>
<p>This Chapter aims to answer the following questions:</p>
<ul>
<li>
<p>How do you explore categorical variables?</p>
<ul>
<li>
<p>Nominal vs.&nbsp;Ordinal</p>
</li><li>
<p>Tests of Association</p>
</li><li>
<p>Measures of Association</p>
</li></ul>
</li><li>
<p>How do you model a categorical target variable?</p>
<ul>
<li>
<p>Logistic Regression</p>
</li><li>
<p>Interpreting Logistic Regression</p>
</li><li>
<p>Assessing Logistic Regression</p>
</li></ul>
</li></ul>
<section id="describing-categorical-data" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="describing-categorical-data"><span class="header-section-number">8.1</span> Describing Categorical Data</h2>
<p>Similar to Chapter <a href="#sec-eda"><span class="quarto-unresolved-ref">sec-eda</span></a>, we need to first explore our data before building any models to try and explain/predict our categorical target variable. With categorical variables, we can look at the distribution of the categories as well as see if this distribution has any association with other variables. For this analysis we are going to still use our Ames housing data. Imagine you worked for a real estate agency and got a bonus check if you sold a house above $175,000 in value. Let’s create this variable in our data:</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AmesHousing)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">make_ordinal_ames</span>()</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> ames <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">row_number</span>())</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> ames <span class="sc">%&gt;%</span> <span class="fu">sample_frac</span>(<span class="fl">0.7</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(ames, train, <span class="at">by =</span> <span class="st">'id'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bonus =</span> <span class="fu">ifelse</span>(Sale_Price <span class="sc">&gt;</span> <span class="dv">175000</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You are interested in what variables might be associated with obtaining a higher chance of getting a bonus (selling a house above $175,000). An association exists between two categorical variables if the distribution of one variable changes when the value of the other categorical changes. If there is no association, the distribution of the first variable is the same regardless of the value of the other variable. For example, if we wanted to know if obtaining a bonus on selling a house in Ames, Iowa was associated with whether the house had central air we could look at the distribution of bonus eligible houses. If we observe that 42% of homes with central air are bonus eligible and 42% of homes without central air are bonus eligible, then it appears that central air has no bearing on whether the home is bonus eligible. However, if instead we observe that only 3% of homes without central air are bonus eligible, but 44% of home with central air are bonus eligible, then it appears that having central air might be related to a home being bonus eligible.</p>
<p>To understand the distribution of categorical variables we need to look at frequency tables. A frequency table shows the number of observations that occur in certain categories or intervals. A one way frequency table examines all the categories of one variable. These are easily visualized with bar charts.</p>
<p>Let’s look at the distribution of both bonus eligibility and central air using the <code>table</code> function. The <code>ggplot</code> function with the <code>geom_bar</code> function allows us to view our data in a bar chart.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Bonus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
1211  840 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Central_Air)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   N    Y 
 147 1904 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Central_Air))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Frequency tables show single variables, but if we want to explore two variables together we look at <strong>cross-tabulation</strong> tables. A cross-tabulation table shows the number of observations for each combination of the row and column variables.</p>
<p>Let’s again examine bonus eligibility, but this time across levels of central air. Again, we can use the <code>table</code> function. The <code>prop.table</code> function allows us to compare two variables in terms of proportions instead of frequencies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       0    1
  N  142    5
  Y 1069  835</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
              0           1
  N 0.069234520 0.002437835
  Y 0.521209166 0.407118479</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Bonus, <span class="at">fill =</span> Central_Air))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above output we can see that 147 homes have no central air with only 5 of them being bonus eligible. However, there are 1904 homes that have central air with 835 of them being bonus eligible. For an even more detailed breakdown we can use the <code>CrossTable</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  2051 

 
                  | train$Bonus 
train$Central_Air |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                N |       142 |         5 |       147 | 
                  |    35.112 |    50.620 |           | 
                  |     0.966 |     0.034 |     0.072 | 
                  |     0.117 |     0.006 |           | 
                  |     0.069 |     0.002 |           | 
------------------|-----------|-----------|-----------|
                Y |      1069 |       835 |      1904 | 
                  |     2.711 |     3.908 |           | 
                  |     0.561 |     0.439 |     0.928 | 
                  |     0.883 |     0.994 |           | 
                  |     0.521 |     0.407 |           | 
------------------|-----------|-----------|-----------|
     Column Total |      1211 |       840 |      2051 | 
                  |     0.590 |     0.410 |           | 
------------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>The advantage of the <code>CrossTable</code> function is that we can easily get not only the frequencies, but the cell, row, and column proportions. For example, the third number in each cell gives us the row proportion. For homes without central air, 96.6% of them are not bonus eligible, while 3.4% of them are. For homes with central air, 56.1% of the homes are not bonus eligible, while 43.9% of them are. This would appear that the distribution of bonus eligible homes changes across levels of central air - a relationship between the two variables. This expected relationship needs to be tested statistically for verification.</p>
</section>
<section id="tests-of-association" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="tests-of-association"><span class="header-section-number">8.2</span> Tests of Association</h2>
<p>Much like in Chapter <a href="#sec-slr"><span class="quarto-unresolved-ref">sec-slr</span></a> we have statistical tests to evaluate relationships between two categorical variables. The null hypothesis for these statistical tests is that the two variables have no association - the distribution of one variable does not change across levels of another variable. The alternative hypothesis is an association between the two variables - the distribution of one variable changes across levels of another variable.</p>
<p>These statistical tests follow a <span class="math inline">\(\chi^2\)</span>-distribution. The <span class="math inline">\(\chi^2\)</span>-distribution is a distribution that has the following characteristics:</p>
<ul>
<li>
<p>Bounded below by 0</p>
</li><li>
<p>Right-skewed</p>
</li><li>
<p>One set of degrees of freedom</p>
</li></ul>
<p>A plot of a variety of <span class="math inline">\(\chi^2\)</span>-distributions is shown here:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Two common <span class="math inline">\(\chi^2\)</span> tests are the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests. They compare the observed count of observations in each cell of a cross-tabulation table between two variables to their expected count <strong>if</strong> there was no relationship. The expected cell count applies the overall distribution of one variable across all the levels of the other variable. For example, overall 59% of all homes are not bonus eligible. <strong>If</strong> that were to apply to every level of central air, then the 140 homes without central air would be expected to have 86.73 ( $ = 147 $ ) of them would be bonus eligible while 60.27 ( $ = 147 $ ) of them would not be bonus eligible. We actually observe 142 and 5 homes for each of these categories respectively. The further the observed data is from the expected data, the more evidence we have that there is a relationship between the two variables.</p>
<p>The test statistic for the Pearson <span class="math inline">\(\chi^2\)</span> test is the following:</p>
<p><span class="math display">\[
\chi^2_P = \sum_{i=1}^R \sum_{j=1}^C \frac{(Obs_{i,j} - Exp_{i,j})^2}{Exp_{i,j}}
\]</span> From the equation above, the closer that the observed count of each cross-tabulation table cell to the expected count, the smaller the test statistic. As with all previous hypothesis tests, the smaller the test statistic, the larger the p-value, implying less evidence for the alternative hypothesis.</p>
<p>Let’s examine the relationship between central air and bonus eligibility using the <code>chisq.test</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(train$Central_Air, train$Bonus)
X-squared = 90.686, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The above results shows an extremely small p-value that is below any reasonable significance level. This implies that we have statistical evidence for a relationship between having central air and bonus eligibility of homes. The p-value comes from a <span class="math inline">\(\chi^2\)</span>-distribution with degrees of freedom that equal the product of the number of rows minus one and the number of columns minus one.</p>
<p>Another common test is the Likelihood Ratio test. The test statistic for this is the following:</p>
<p><span class="math display">\[
\chi^2_L = 2 \times \sum_{i=1}^R \sum_{j=1}^C Obs_{i,j} \times \log(\frac{Obs_{i,j}}{Exp_{i,j}})
\]</span></p>
<p>The p-value comes from a <span class="math inline">\(\chi^2\)</span>-distribution with degrees of freedom that equal the product of the number of rows minus one and the number of columns minus one. Both of the above tests have a sample size requirement. The sample size requirement is 80% or more of the cells in the cross-tabulation table need <strong>expected</strong> count larger than 5.</p>
<p>For smaller sample sizes, this might be hard to meet. In those situations, we can use a more computationally expensive test called Fisher’s exact test. This test calculates every possible permutation of the data being evaluated to calculate the p-value without any distributional assumptions. To perform this test we can use the <code>fisher.test</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  table(train$Central_Air, train$Bonus)
p-value &lt; 2.2e-16
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  9.213525 69.646380
sample estimates:
odds ratio 
  22.16545 </code></pre>
</div>
</div>
<p>We see the same results as with the Pearson test because the assumptions were met for sample size.</p>
<p>Both the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests can handle any type of categorical variable either ordinal, nominal, or both. However, ordinal variables provide us extra information since the order of the categories actually matters compared to nominal. We can test for even more with ordinal variables against other ordinal variables whether two ordinal variables have a <strong>linear relationship</strong> as compared to just a general one. An ordinal test for association is the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test. The test statistic for the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test is the following:</p>
<p><span class="math display">\[
\chi^2_{MH} = (n-1)r^2
\]</span> where <span class="math inline">\(r^2\)</span> is the Pearson correlation between the column and row variables. This test follows a <span class="math inline">\(\chi^2\)</span>-distribution with only one degree of freedom.</p>
<p>Since both the central air and bonus eligibility variables are binary, they are ordinal. Since they are both ordinal, we should use the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test with the <code>CMHtest</code> function. In the main output table, the first row is the Mantel-Haenszel <span class="math inline">\(\chi^2\)</span> test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">CMHtest</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))<span class="sc">$</span>table[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Chisq           Df         Prob 
9.230619e+01 1.000000e+00 7.425180e-22 </code></pre>
</div>
</div>
<p>From here we can see another extremely small p-value as we saw in earlier, more general <span class="math inline">\(\chi^2\)</span> tests.</p>
</section>
<section id="measures-of-association" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="measures-of-association"><span class="header-section-number">8.3</span> Measures of Association</h2>
<p>Tests of association are best designed for just that, testing the existence of an association between two categorical variables. However, just like we saw in Chapter <a href="#sec-eda"><span class="quarto-unresolved-ref">sec-eda</span></a>, hypothesis tests are impacted by sample size. When we have the same sample size, tests of association can rank significance of variables with p-values. However, when sample sizes are not the same between two tests, the tests of association are not best for comparing the strength of an association. In those scenarios, we have measures of strength of association that can be compared across any sample size.</p>
<p>Measures of association were not designed to test if an association exists, as that is what statistical testing is for. They are designed to measure the strength of association. There are dozens of these measures. Three of the most common are the following: - Odds Ratios (only for comparing two binary variables) - Cramer’s V (able to compare nominal variables with any number of categories) - Spearman’s Correlation (able to compare ordinal variables with any number of categories)</p>
<p>An <strong>odds ratio</strong> indicates how much more likely, with respect to <strong>odds</strong>, a certain event occurs in one group relative to its occurrence in another group. The odds of an event occurring is <em>not</em> the same as the probability that an event occurs. The odds of an event occurring is the probability the event occurs divided by the probability that event does not occur.</p>
<p><span class="math display">\[
Odds = \frac{p}{1-p}
\]</span></p>
<p>Let’s again examine the cross-tabulation table between central air and bonus eligibility.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
| Chi-square contribution |
|           N / Row Total |
|           N / Col Total |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  2051 

 
                  | train$Bonus 
train$Central_Air |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                N |       142 |         5 |       147 | 
                  |    35.112 |    50.620 |           | 
                  |     0.966 |     0.034 |     0.072 | 
                  |     0.117 |     0.006 |           | 
                  |     0.069 |     0.002 |           | 
------------------|-----------|-----------|-----------|
                Y |      1069 |       835 |      1904 | 
                  |     2.711 |     3.908 |           | 
                  |     0.561 |     0.439 |     0.928 | 
                  |     0.883 |     0.994 |           | 
                  |     0.521 |     0.407 |           | 
------------------|-----------|-----------|-----------|
     Column Total |      1211 |       840 |      2051 | 
                  |     0.590 |     0.410 |           | 
------------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>Let’s look at the row without central air. The probability that a home without central air is not bonus eligible is 96.6%. That implies that the odds of not being bonus eligible in homes without central air is 28.41 (= 0.966/0.034). For homes with central air, the odds of not being bonus eligible are 1.28 (= 0.561/0.439). The odds ratio between these two would be approximately 22.2 (= 28.41/1.28). In other words, homes without central air are 22.2 times more likely (in terms of odds) to not be bonus eligible as compared to homes with central air. This relationship is intuitive based on the numbers we have seen. Without going into details, it can also be shown that homes with central air are 22.2 times as likely (in terms of odds) to be bonus eligible.</p>
<p>We can use the <code>OddsRatio</code> function to get these same results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">OddsRatio</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.18335</code></pre>
</div>
</div>
<p><strong>Cramer’s V</strong> is another measure of strength of association. Cramer’s V is calculated as follows:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2_P/n}{\min(Rows-1, Columns-1)}}
\]</span></p>
<p>Cramer’s V is bounded between 0 and 1 for every comparison other than two binary variables. For two binary variables being compared the bounds are -1 to 1. The idea is still the same for both. The further the value is from 0, the stronger the relationship. Unfortunately, unlike <span class="math inline">\(R^2\)</span>, Cramer’s V has no interpretative value. It can only be used for comparison.</p>
<p>We use the <code>assocstats</code> function to get the Cramer’s V value. This function also provides the Pearson and Likelihood Ratio <span class="math inline">\(\chi^2\)</span> tests as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">assocstats</span>(<span class="fu">table</span>(train<span class="sc">$</span>Central_Air, train<span class="sc">$</span>Bonus))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     X^2 df P(&gt; X^2)
Likelihood Ratio 121.499  1        0
Pearson           92.351  1        0

Phi-Coefficient   : 0.212 
Contingency Coeff.: 0.208 
Cramer's V        : 0.212 </code></pre>
</div>
</div>
<p>Lastly, we have Spearman’s correlation. Much like the Mantel-Haenszel test of association was specifically designed for comparing two ordinal variables, Spearman correlation measures the strength of association between two ordinal variables. Spearman is not limited to only categorical data analysis as it was also seen back in Chapter <a href="#sec-diag"><span class="quarto-unresolved-ref">sec-diag</span></a> with detecting heteroskedasticity. Remember, Spearman correlation is a correlation on the ranks of the observations as compared to the actual values of the observations.</p>
<p>The <code>cor.test</code> function that gave us Pearson’s correlation also provides Spearman’s correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> <span class="fu">as.numeric</span>(<span class="fu">ordered</span>(train<span class="sc">$</span>Central_Air)), </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">as.numeric</span>(<span class="fu">ordered</span>(train<span class="sc">$</span>Bonus)), </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  x and y
S = 1132826666, p-value &lt; 2.2e-16
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.2121966 </code></pre>
</div>
</div>
<p>As previously mentioned, these are only a few of the dozens of different measures of association that exist. However, they are the most used ones.</p>
</section>
<section id="introduction-to-logistic-regression" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="introduction-to-logistic-regression"><span class="header-section-number">8.4</span> Introduction to Logistic Regression</h2>
<p>After exploring the categorical target variable, we can move on to modeling the categorical target variable. Logistic regression is a fundamental statistical analysis for data science and analytics. It part of a class of modeling techniques known as classification models since they are trying to predict categorical target variables. This target variable can be binary, ordinal, or even nominal in its structure. The primary focus will be binary logistic regression. It is the most common type of logistic regression, and sets up the foundation for both ordinal and nominal logistic regression.</p>
<p>Ordinary least squares regression is not the best approach to modeling categorical target variables. Mathematically, it can be shown that with a binary target variable coded as 0 and 1, an OLS linear regression model will produce the <strong>linear probability model</strong>.</p>
<section id="linear-probability-model" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="linear-probability-model"><span class="header-section-number">8.4.1</span> Linear Probability Model</h3>
<p>The linear probability model is not as widely used since probabilities do not tend to follow the properties of linearity in relation to their predictors. Also, the linear probability model possibly produces predictions outside of the bounds of 0 and 1 (where probabilities should be!). For completeness sake however, here is the linear probability model using the <code>lm</code> function to try and predict bonus eligibility.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lp.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, <span class="at">data =</span> train)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(train, <span class="fu">plot</span>(<span class="at">x =</span> Gr_Liv_Area, <span class="at">y =</span> Bonus,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">main =</span> <span class="st">'OLS Regression?'</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">'Greater Living Area (Sqft)'</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">'Bonus Eligibility'</span>))</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lp.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even though it doesn’t appear to really look like our data, let’s fit this linear probability model anyway for completeness sake.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lp.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, <span class="at">data =</span> train)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lp.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Bonus ~ Gr_Liv_Area, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.70766 -0.29160 -0.09983  0.39432  0.86198 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.149e-01  2.776e-02  -14.94   &lt;2e-16 ***
Gr_Liv_Area  5.534e-04  1.765e-05   31.36   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4044 on 2049 degrees of freedom
Multiple R-squared:  0.3243,    Adjusted R-squared:  0.324 
F-statistic: 983.6 on 1 and 2049 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstandard</span>(lp.model),</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Standardized Residuals"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Normal Scores"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"QQ-Plot of Residuals"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstandard</span>(lp.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lp.model), <span class="fu">resid</span>(lp.model), </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Residuals"</span>, <span class="at">xlab=</span><span class="st">"Predicted Values"</span>, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Residuals of Linear Probability Model"</span>) </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-categorical_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we can see from the charts above, the assumptions of ordinary least squares don’t really hold in this situation. Therefore, we should be careful interpreting the results of the model. Maybe a better model won’t have these problems?</p>
</section>
<section id="binary-logistic-regression" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="binary-logistic-regression"><span class="header-section-number">8.4.2</span> Binary Logistic Regression</h3>
<p>Due to the limitations of the linear probability model, people typically just use the binary logistic regression model. The logistic regression model does not have the limitations of the linear probability model. The outcome of the logistic regression model is the probability of getting a 1 in a binary variable. That probability is calculated as follows:</p>
<p><span class="math display">\[
p_i = \frac{1}{1+e^{-(\beta_0 + \beta_1x_{1,i} + \cdots + \beta_k x_{k,i})}}
\]</span></p>
<p>This function has the desired properties for predicting probabilities. The predicted probability from the above equation will always be between 0 and 1. The parameter estimates do not enter the function linearly (this is a non-linear regression model), and the rate of change of the probability varies as the predictor variables vary as seen in Figure <a href="#fig-logistic">Figure&nbsp;<span class="quarto-unresolved-ref">fig-logistic</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-logistic" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/logistic.png" class="img-fluid figure-img" style="width:50.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.1: Example of a Logistic Curve</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To create a linear model, a <strong>link function</strong> is applied to the probabilities. The specific link function for logistic regression is called the <strong>logit</strong> function.</p>
<p><span class="math display">\[
logit(p_i) = \log(\frac{p_i}{1-p_i}) = \beta_0 + \beta_1x_{1,i} + \cdots + \beta_k x_{k,i}
\]</span></p>
<p>The relationship between the predictor variables and the logits are linear in nature as the logits themselves are unbounded. This structure looks much more like our linear regression model structure. However, logistic regression does not use OLS to estimate the coefficients in our model. OLS requires residuals which the logistic regression model does not provide. The target variable is binary in nature, but the predictions are probabilities. Therefore, we cannot calculate a traditional residual. Instead, logistic regression uses maximum likelihood estimation. This is not covered here.</p>
<p>There are two main assumptions for logistic regression:</p>
<ol type="1">
<li>Independence of observations</li>
<li>Linearity of the logit</li>
</ol>
<p>The first assumption of independence is the same as we had for linear regression. The second assumption implies that the logistic function transformation (the logit) actually makes a linear relationship with our predictor variables. This assumption can be tested, but will not be covered in this brief introduction to logistic regression.</p>
<p>Let’s build a logistic regression model. We will use the <code>glm</code> function to do this. The <code>glm</code> function has a similar structure to the <code>lm</code> function. The main difference is the <code>family = binomial(link = "logit")</code> option to specify that we are uses a logistic regression model. Again, there are many different link functions, but only the logistic link function (the logit) is being used here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ames_logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> train, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ames_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Bonus ~ Gr_Liv_Area, family = binomial(link = "logit"), 
    data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-5.5796  -0.6942  -0.3647   0.8060   2.1857  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -6.1348858  0.2757473  -22.25   &lt;2e-16 ***
Gr_Liv_Area  0.0038463  0.0001799   21.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2775.8  on 2050  degrees of freedom
Residual deviance: 1926.4  on 2049  degrees of freedom
AIC: 1930.4

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Let’s examine the above output. Scanning down the output, you can see the actual logistic regression equation for the variable <code>Gr_Liv_Area</code>. Here we can see that it appears to be a significant variable at predicting bonus eligibility. However, the coefficient reported does not have the same usable interpretation as in linear regression. An increase of one unit of greater living area square footage is linearly related to the logit <strong>not</strong> the probability of bonus eligibility. We can transform this coefficient to make it more interpretable. A single unit increase in greater living area square footage <strong>does</strong> have a <span class="math inline">\(100 \times (e^\hat{\beta}-1)\%\)</span> increase in the average <strong>odds</strong> of bonus eligibility. We can use a combination of the <code>exp</code> and <code>coef</code> functions to obtain this number.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(ames_logit), <span class="fu">confint</span>(ames_logit)))<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                              2.5 %      97.5 %
(Intercept) -99.7834027 -99.8755103 -99.6328865
Gr_Liv_Area   0.3853699   0.3508132   0.4216532</code></pre>
</div>
</div>
<p>In other words, every additional square foot in greater living area in the home leads to an average increase in odds of 0.385% to be bonus eligible.</p>
</section>
<section id="adding-categorical-variables" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="adding-categorical-variables"><span class="header-section-number">8.4.3</span> Adding Categorical Variables</h3>
<p>Similar to linear regression as we learned in Chapter <a href="#sec-mlr"><span class="quarto-unresolved-ref">sec-mlr</span></a>, logistic regression can have both continuous and categorical predictors for our categorical target variable. Let’s add both central air as well as number of fireplaces to our logistic regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ames_logit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> Gr_Liv_Area <span class="sc">+</span> Central_Air <span class="sc">+</span> <span class="fu">factor</span>(Fireplaces), </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> train, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ames_logit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Bonus ~ Gr_Liv_Area + Central_Air + factor(Fireplaces), 
    family = binomial(link = "logit"), data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-5.4340  -0.6467  -0.2822   0.6610   2.8866  

Coefficients:
                      Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -9.970e+00  6.549e-01 -15.223  &lt; 2e-16 ***
Gr_Liv_Area          3.759e-03  2.031e-04  18.506  &lt; 2e-16 ***
Central_AirY         3.564e+00  5.310e-01   6.711 1.93e-11 ***
factor(Fireplaces)1  9.822e-01  1.253e-01   7.837 4.60e-15 ***
factor(Fireplaces)2  6.734e-01  2.406e-01   2.799  0.00513 ** 
factor(Fireplaces)3 -3.993e-02  8.711e-01  -0.046  0.96344    
factor(Fireplaces)4  9.025e+00  3.247e+02   0.028  0.97783    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2775.8  on 2050  degrees of freedom
Residual deviance: 1746.2  on 2044  degrees of freedom
AIC: 1760.2

Number of Fisher Scoring iterations: 11</code></pre>
</div>
</div>
<p>Just like with linear regression, categorical predictor variables are a comparison between two categories. Again, the coefficients from the logistic regression model need to be transformed to be interpreted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(ames_logit2), <span class="fu">confint</span>(ames_logit2)))<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         2.5 %        97.5 %
(Intercept)         -9.999532e+01  -99.9988238   -99.9843742
Gr_Liv_Area          3.766413e-01    0.3376191     0.4175879
Central_AirY         3.429115e+03 1264.8396217 11177.2021480
factor(Fireplaces)1  1.670410e+02  108.9856565   241.6360910
factor(Fireplaces)2  9.607987e+01   22.4764491   214.9571145
factor(Fireplaces)3 -3.914247e+00  -81.9507819   497.4825425
factor(Fireplaces)4  8.308750e+05 -100.0000000            NA</code></pre>
</div>
</div>
<p>Let’s use the first fireplace variable as an example. A home with one fireplace has, on average, 167.04% higher odds of being bonus eligible as compared to a home with zero fireplaces.</p>
</section>
<section id="model-assessment" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="model-assessment"><span class="header-section-number">8.4.4</span> Model Assessment</h3>
<p>There are dozens of different ways to evaluate a logistic regression model. We will cover one popular way here - concordance. Counting the number of <strong>concordant</strong>, <strong>discordant</strong>, and <strong>tied</strong> pairs is a way to to assess how well the model fits the data.</p>
<p>To find concordant, discordant, and tied pairs, we must compare all of the 0’s in the target variable to all of the 1’s. For our example, we will compare every pair of homes where one home is bonus eligible and one is not (every 0 and 1 pair). A <strong>concordant</strong> pair is a 0 and 1 pair where the bonus eligible home (the 1 in our model) has a higher predicted probability than the non-bonus eligible home (the 0 in our model) - our model successfully ordered these two observations by probability. It does not matter what the actual predicted probability values are as long as the bonus eligible home has a higher predicted probability than the non-bonus eligible home. A <strong>discordant</strong> pair is a 0 and 1 pair where the bonus eligible home (the 1 in our model) has a lower predicted probability than the non-bonus eligible home (the 0 in our model) - our model unsuccessfully ordered the homes. It does not matter what the actual predicted probability values are as long as the bonus eligible home has a lower predicted probability than the non-bonus eligible home. A <strong>tied</strong> pair is a 0 and 1 pair where the bonus eligible home has the same predicted probability as the non-bonus eligible home - the model is confused and sees these two different things as the same. In general, you want a high percentage of concordant pairs and low percentages of discordant and tied pairs.</p>
<p>We can use the <code>Concordance</code> function to obtain these values on our predictions from the <code>predict</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(InformationValue)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Concordance</span>(train<span class="sc">$</span>Bonus, <span class="fu">predict</span>(ames_logit, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Concordance
[1] 0.862933

$Discordance
[1] 0.137067

$Tied
[1] -5.551115e-17

$Pairs
[1] 1017240</code></pre>
</div>
</div>
<p>From the above output we have a concordance of 86.3% for our model. There is no good or bad value as this can only be compared with another model to see which is better. Let’s compare this to our model with the categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Concordance</span>(train<span class="sc">$</span>Bonus, <span class="fu">predict</span>(ames_logit2, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Concordance
[1] 0.8839182

$Discordance
[1] 0.1160818

$Tied
[1] 4.163336e-17

$Pairs
[1] 1017240</code></pre>
</div>
</div>
<p>We can see that the model with categorical predictors added to it has a higher concordance at 88.4%. That implies that our model is correctly able to rank our observations 88.4% of the time. This is <strong>NOT</strong> the same thing as saying our model is 88.4% accurate. Accuracy (which is not covered here) deals with a prediction being correct or incorrect. Concordance is only measuring how often we are able to predict 1’s with higher probability than 0’s - again, correctly ranking the observations.</p>
</section>
<section id="variable-selection-and-regularized-regression" class="level3" data-number="8.4.5">
<h3 data-number="8.4.5" class="anchored" data-anchor-id="variable-selection-and-regularized-regression"><span class="header-section-number">8.4.5</span> Variable Selection and Regularized Regression</h3>
<p>As with linear regression in Chapters <a href="#sec-mlr"><span class="quarto-unresolved-ref">sec-mlr</span></a> and <a href="#sec-sel"><span class="quarto-unresolved-ref">sec-sel</span></a>, logistic regression uses the same approaches to doing variable selection. In fact, the same function are used as well. Let’s use the <code>step</code> function to apply a forward and backward selection to the logistic regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>train_sel_log <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Bonus, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>         Lot_Area,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>         Street,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>         Bldg_Type,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>         House_Style,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>         Overall_Qual,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>         Roof_Style,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>         Central_Air,</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>         First_Flr_SF,</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>         Second_Flr_SF,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>         Full_Bath,</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>         Half_Bath,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>         Fireplaces,</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>         Garage_Area,</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>         Gr_Liv_Area, </span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>         TotRms_AbvGrd) <span class="sc">%&gt;%</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace</span>(<span class="fu">is.na</span>(.), <span class="dv">0</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> . , <span class="at">data =</span> train_sel_log)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Bonus <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_sel_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>for.model <span class="ot">&lt;-</span> <span class="fu">step</span>(empty.model,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> <span class="fu">formula</span>(empty.model),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">upper =</span> <span class="fu">formula</span>(full.model)),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">dim</span>(train_sel_log)[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=2918.59
Bonus ~ 1

                Df Deviance    AIC
+ Overall_Qual   9   234.74 1453.0
+ Full_Bath      1   320.51 2030.8
+ Gr_Liv_Area    1   335.11 2122.1
+ Garage_Area    1   367.62 2312.0
+ First_Flr_SF   1   396.15 2465.3
+ Fireplaces     1   415.26 2561.9
+ TotRms_AbvGrd  1   422.53 2597.6
+ House_Style    7   444.22 2745.9
+ Half_Bath      1   459.40 2769.1
+ Second_Flr_SF  1   461.26 2777.4
+ Central_Air    1   473.64 2831.7
+ Lot_Area       1   478.42 2852.3
+ Bldg_Type      4   477.21 2870.0
&lt;none&gt;               495.97 2918.6
+ Street         1   495.86 2925.8
+ Roof_Style     5   491.40 2937.7

Step:  AIC=1452.99
Bonus ~ Overall_Qual

                Df Deviance    AIC
+ Full_Bath      1   203.87 1171.4
+ Gr_Liv_Area    1   208.62 1218.7
+ First_Flr_SF   1   218.70 1315.5
+ Garage_Area    1   223.10 1356.3
+ TotRms_AbvGrd  1   223.12 1356.5
+ Fireplaces     1   223.33 1358.5
+ Lot_Area       1   225.07 1374.3
+ Bldg_Type      4   227.31 1417.6
+ Second_Flr_SF  1   230.98 1427.5
+ Half_Bath      1   231.81 1434.8
+ Central_Air    1   233.55 1450.2
&lt;none&gt;               234.74 1453.0
+ Street         1   234.30 1456.8
+ House_Style    7   230.28 1467.1
+ Roof_Style     5   234.18 1486.2

Step:  AIC=1171.42
Bonus ~ Overall_Qual + Full_Bath

                Df Deviance    AIC
+ Fireplaces     1   193.70 1074.1
+ First_Flr_SF   1   195.11 1089.0
+ Gr_Liv_Area    1   196.26 1101.0
+ Lot_Area       1   197.22 1111.0
+ Bldg_Type      4   195.24 1113.2
+ Garage_Area    1   197.63 1115.3
+ Half_Bath      1   201.31 1153.1
+ TotRms_AbvGrd  1   202.51 1165.3
+ Central_Air    1   202.61 1166.4
&lt;none&gt;               203.87 1171.4
+ Street         1   203.38 1174.2
+ Second_Flr_SF  1   203.85 1178.9
+ House_Style    7   201.34 1199.2
+ Roof_Style     5   203.40 1204.8

Step:  AIC=1074.14
Bonus ~ Overall_Qual + Full_Bath + Fireplaces

                Df Deviance    AIC
+ Garage_Area    1   188.96 1030.9
+ First_Flr_SF   1   189.34 1035.0
+ Bldg_Type      4   187.45 1037.3
+ Lot_Area       1   190.10 1043.3
+ Gr_Liv_Area    1   190.64 1049.1
+ Half_Bath      1   192.04 1064.0
&lt;none&gt;               193.70 1074.1
+ Central_Air    1   193.02 1074.5
+ Street         1   193.35 1078.0
+ TotRms_AbvGrd  1   193.42 1078.7
+ Second_Flr_SF  1   193.69 1081.7
+ House_Style    7   190.38 1092.0
+ Roof_Style     5   193.16 1106.5

Step:  AIC=1030.9
Bonus ~ Overall_Qual + Full_Bath + Fireplaces + Garage_Area

                Df Deviance    AIC
+ Bldg_Type      4   183.72 1003.8
+ First_Flr_SF   1   186.24 1008.8
+ Lot_Area       1   186.46 1011.2
+ Gr_Liv_Area    1   186.87 1015.7
+ Half_Bath      1   187.55 1023.2
&lt;none&gt;               188.96 1030.9
+ Street         1   188.68 1035.5
+ Central_Air    1   188.76 1036.3
+ TotRms_AbvGrd  1   188.78 1036.6
+ Second_Flr_SF  1   188.96 1038.5
+ House_Style    7   186.42 1056.5
+ Roof_Style     5   188.20 1060.8

Step:  AIC=1003.78
Bonus ~ Overall_Qual + Full_Bath + Fireplaces + Garage_Area + 
    Bldg_Type

                Df Deviance     AIC
+ First_Flr_SF   1   181.17  982.68
+ Half_Bath      1   181.99  991.99
+ Gr_Liv_Area    1   182.00  992.09
+ Lot_Area       1   182.09  993.12
&lt;none&gt;               183.72 1003.78
+ Street         1   183.36 1007.35
+ Central_Air    1   183.60 1009.98
+ TotRms_AbvGrd  1   183.66 1010.71
+ Second_Flr_SF  1   183.72 1011.35
+ House_Style    7   180.41 1019.87
+ Roof_Style     5   182.90 1032.69

Step:  AIC=982.68
Bonus ~ Overall_Qual + Full_Bath + Fireplaces + Garage_Area + 
    Bldg_Type + First_Flr_SF

                Df Deviance     AIC
+ Half_Bath      1   177.46  947.94
+ Second_Flr_SF  1   180.10  978.18
+ Lot_Area       1   180.24  979.73
+ Gr_Liv_Area    1   180.28  980.18
&lt;none&gt;               181.17  982.68
+ Street         1   180.77  985.80
+ House_Style    7   176.95  987.73
+ Central_Air    1   181.06  989.10
+ TotRms_AbvGrd  1   181.16  990.19
+ Roof_Style     5   179.76 1004.77

Step:  AIC=947.94
Bonus ~ Overall_Qual + Full_Bath + Fireplaces + Garage_Area + 
    Bldg_Type + First_Flr_SF + Half_Bath

                Df Deviance    AIC
+ Lot_Area       1   176.75 947.31
&lt;none&gt;               177.46 947.94
+ TotRms_AbvGrd  1   177.03 950.49
+ Street         1   177.09 951.18
+ Central_Air    1   177.43 955.17
+ Gr_Liv_Area    1   177.46 955.45
+ Second_Flr_SF  1   177.46 955.56
+ Roof_Style     5   175.95 968.54
+ House_Style    7   174.78 970.01

Step:  AIC=947.31
Bonus ~ Overall_Qual + Full_Bath + Fireplaces + Garage_Area + 
    Bldg_Type + First_Flr_SF + Half_Bath + Lot_Area

                Df Deviance    AIC
&lt;none&gt;               176.75 947.31
+ TotRms_AbvGrd  1   176.32 949.96
+ Street         1   176.54 952.49
+ Central_Air    1   176.72 954.56
+ Gr_Liv_Area    1   176.73 954.71
+ Second_Flr_SF  1   176.75 954.89
+ Roof_Style     5   175.25 968.01
+ House_Style    7   174.09 969.62</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>back.model <span class="ot">&lt;-</span> <span class="fu">step</span>(full.model,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> <span class="fu">formula</span>(empty.model),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">upper =</span> <span class="fu">formula</span>(full.model)),</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">dim</span>(train_sel_log)[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=1016.59
Bonus ~ Lot_Area + Street + Bldg_Type + House_Style + Overall_Qual + 
    Roof_Style + Central_Air + First_Flr_SF + Second_Flr_SF + 
    Full_Bath + Half_Bath + Fireplaces + Garage_Area + Gr_Liv_Area + 
    TotRms_AbvGrd

                Df Deviance     AIC
- House_Style    7   174.31  995.05
- Roof_Style     5   173.24  997.67
- Gr_Liv_Area    1   171.63 1009.07
- Central_Air    1   171.64 1009.12
- Second_Flr_SF  1   171.71 1009.95
- First_Flr_SF   1   171.84 1011.48
- Street         1   171.89 1012.09
- TotRms_AbvGrd  1   171.94 1012.72
- Lot_Area       1   172.08 1014.43
&lt;none&gt;               171.62 1016.59
- Garage_Area    1   172.50 1019.38
- Half_Bath      1   173.37 1029.70
- Fireplaces     1   173.90 1035.95
- Bldg_Type      4   177.07 1050.13
- Full_Bath      1   187.25 1187.64
- Overall_Qual   9   217.74 1436.04

Step:  AIC=995.05
Bonus ~ Lot_Area + Street + Bldg_Type + Overall_Qual + Roof_Style + 
    Central_Air + First_Flr_SF + Second_Flr_SF + Full_Bath + 
    Half_Bath + Fireplaces + Garage_Area + Gr_Liv_Area + TotRms_AbvGrd

                Df Deviance     AIC
- Roof_Style     5   175.81  974.50
- Central_Air    1   174.35  987.91
- Gr_Liv_Area    1   174.43  988.84
- Second_Flr_SF  1   174.49  989.53
- Street         1   174.53  989.99
- TotRms_AbvGrd  1   174.74  992.45
- Lot_Area       1   174.80  993.19
- First_Flr_SF   1   174.89  994.22
&lt;none&gt;               174.31  995.05
- Garage_Area    1   175.57 1002.23
- Fireplaces     1   176.38 1011.68
- Half_Bath      1   176.86 1017.24
- Bldg_Type      4   179.33 1022.77
- Full_Bath      1   191.76 1183.08
- Overall_Qual   9   222.96 1431.28

Step:  AIC=974.5
Bonus ~ Lot_Area + Street + Bldg_Type + Overall_Qual + Central_Air + 
    First_Flr_SF + Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + 
    Garage_Area + Gr_Liv_Area + TotRms_AbvGrd

                Df Deviance     AIC
- Central_Air    1   175.85  967.29
- Gr_Liv_Area    1   175.91  968.02
- Second_Flr_SF  1   175.97  968.79
- Street         1   176.01  969.19
- TotRms_AbvGrd  1   176.30  972.55
- Lot_Area       1   176.31  972.65
- First_Flr_SF   1   176.31  972.66
&lt;none&gt;               175.81  974.50
- Garage_Area    1   177.04  981.15
- Fireplaces     1   177.86  990.64
- Half_Bath      1   178.19  994.42
- Bldg_Type      4   180.75 1000.81
- Full_Bath      1   193.59 1164.44
- Overall_Qual   9   224.35 1405.92

Step:  AIC=967.29
Bonus ~ Lot_Area + Street + Bldg_Type + Overall_Qual + First_Flr_SF + 
    Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + Garage_Area + 
    Gr_Liv_Area + TotRms_AbvGrd

                Df Deviance     AIC
- Gr_Liv_Area    1   175.95  960.84
- Second_Flr_SF  1   176.01  961.59
- Street         1   176.03  961.83
- TotRms_AbvGrd  1   176.34  965.38
- First_Flr_SF   1   176.35  965.52
- Lot_Area       1   176.35  965.52
&lt;none&gt;               175.85  967.29
- Garage_Area    1   177.19  975.25
- Fireplaces     1   177.95  984.00
- Half_Bath      1   178.34  988.55
- Bldg_Type      4   180.88  994.63
- Full_Bath      1   193.82 1159.28
- Overall_Qual   9   224.36 1398.33

Step:  AIC=960.84
Bonus ~ Lot_Area + Street + Bldg_Type + Overall_Qual + First_Flr_SF + 
    Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + Garage_Area + 
    TotRms_AbvGrd

                Df Deviance     AIC
- Street         1   176.13  955.40
- Second_Flr_SF  1   176.14  955.45
- Lot_Area       1   176.44  959.00
- TotRms_AbvGrd  1   176.54  960.09
&lt;none&gt;               175.95  960.84
- Garage_Area    1   177.32  969.16
- Fireplaces     1   178.04  977.46
- Half_Bath      1   178.50  982.75
- Bldg_Type      4   180.94  987.72
- First_Flr_SF   1   179.15  990.17
- Full_Bath      1   193.95 1153.02
- Overall_Qual   9   224.57 1392.65

Step:  AIC=955.4
Bonus ~ Lot_Area + Bldg_Type + Overall_Qual + First_Flr_SF + 
    Second_Flr_SF + Full_Bath + Half_Bath + Fireplaces + Garage_Area + 
    TotRms_AbvGrd

                Df Deviance     AIC
- Second_Flr_SF  1   176.32  949.96
- TotRms_AbvGrd  1   176.75  954.89
- Lot_Area       1   176.78  955.30
&lt;none&gt;               176.13  955.40
- Garage_Area    1   177.53  963.91
- Fireplaces     1   178.25  972.22
- Half_Bath      1   178.71  977.53
- Bldg_Type      4   181.03  981.12
- First_Flr_SF   1   179.28  984.03
- Full_Bath      1   194.12 1147.16
- Overall_Qual   9   224.74 1386.53

Step:  AIC=949.96
Bonus ~ Lot_Area + Bldg_Type + Overall_Qual + First_Flr_SF + 
    Full_Bath + Half_Bath + Fireplaces + Garage_Area + TotRms_AbvGrd

                Df Deviance     AIC
- TotRms_AbvGrd  1   176.75  947.31
&lt;none&gt;               176.32  949.96
- Lot_Area       1   177.03  950.49
- Garage_Area    1   177.78  959.22
- Fireplaces     1   178.72  970.00
- Bldg_Type      4   181.35  977.15
- Half_Bath      1   180.23  987.27
- First_Flr_SF   1   180.28  987.88
- Full_Bath      1   198.37 1183.99
- Overall_Qual   9   225.34 1384.40

Step:  AIC=947.31
Bonus ~ Lot_Area + Bldg_Type + Overall_Qual + First_Flr_SF + 
    Full_Bath + Half_Bath + Fireplaces + Garage_Area

               Df Deviance     AIC
&lt;none&gt;              176.75  947.31
- Lot_Area      1   177.46  947.94
- Garage_Area   1   178.30  957.58
- Fireplaces    1   178.97  965.27
- Bldg_Type     4   181.72  973.64
- Half_Bath     1   180.24  979.73
- First_Flr_SF  1   180.34  980.88
- Full_Bath     1   199.82 1191.34
- Overall_Qual  9   225.73 1380.31</code></pre>
</div>
</div>
<p>In the above two approaches we used the BIC selection criteria. Here both forward and backward selection actually picked the same model. Let’s check the concordance of this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Concordance</span>(train<span class="sc">$</span>Bonus, <span class="fu">predict</span>(back.model, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Concordance
[1] 0.9612668

$Discordance
[1] 0.03873324

$Tied
[1] -2.081668e-17

$Pairs
[1] 1017240</code></pre>
</div>
</div>
<p>Not surprisingly, this model outperforms the previous model that we had with a concordance of 96.1%.</p>
<p>Although not covered in detail here, regularized regression can also be applied to logistic regression to get a different view. This might be helpful with the multicollinearity present in these predictor variables. Again, we can use the <code>glmnet</code> function with the addition of a <code>family = "binomial"</code> option.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-model_building_scoring.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Building &amp; Scoring for Prediction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>